### ISSUE TITLE
Got 403 Forbidden when achieving the data

### ISSUE THREAD

**Issue by fcxfcx** [cschell/who-is-alyx#2]
When I try to use dvc to get the data, the progress bar is stuck. So I try to directly use the URL in the config file to achieve the data and it returns a 403 Forbidden error.

**Comment by cschell** [comment]
Hey @fcxfcx , what do you mean by "the progress bar is stuck"? It can take DVC some time to start downloading, so you might have to wait for some time before the actual downloading starts.

> So I try to directly use the URL in the config file to achieve the data and it returns a 403 Forbidden error.

That's to be expected, directly accessing the url won't work, since you cannot access a DVC storage like that.

-chris

**Comment by fcxfcx** [comment]
After waiting for some time, I tried to download the data again and it worked successfully. Thanks for your reply!
